indexing-settings:
  sites:
    - url: https://www.playback.ru/
      name: PlayBack.Ru
    - url: https://www.rosavillage.ru/
      name: Rosa Village
    - url: https://xn--80aeeirqv7i.xn--p1ai/
      name: JumpWay


server:
  port: 8080
spring:
  datasource:
    username: user1
    password: user1
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
logging:
  level:
    searchengine: debug
